### ISSUE TITLE
Error: Cannot find module 'grunt-legacy-util'

### ISSUE THREAD

**Issue by pezholio** [FineUploader/fine-uploader#1165]
I've just tried to build fine-uploader, but after following the instructions, I get to `grunt package` and I get the following error:

```
module.js:340
    throw err;
          ^
Error: Cannot find module 'grunt-legacy-util'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/Users/stuart/Documents/fine-uploader/node_modules/grunt/lib/grunt.js:26:12)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/grunt-cli/bin/grunt:45:1)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
```

I've tried installing `grunt-legacy-util`, but I still get the same error. Any ideas where I'm going wrong?

**Comment by cfalguiere** [comment]
I got the same error when grunt is run from a mounted dir (vagrant's shared folder)

vagrant@dev:~$ grunt --version 
grunt-cli v0.1.13
==> OK

vagrant@dev:~$ cd /vagrant/
vagrant@dev:/vagrant$ grunt --version 
grunt-cli v0.1.13
==> KO

vagrant@dev:/vagrant$ cd mytodo/
vagrant@dev:/vagrant/mytodo$ grunt --version 
grunt-cli v0.1.13

module.js:340
    throw err;
          ^
Error: Cannot find module 'grunt-legacy-util'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
==> Failed

Here is the installation process I ran before
--- installation process
#provisioning shell ran from vagrant on an ubuntu/trusty64 box 
sudo apt-get update
sudo locale-gen en_US.UTF-8
sudo locale-gen fr_FR.UTF-8
sudo apt-get -y install git
sudo apt-get -y install nodejs
sudo apt-get install nodejs-legacy # required on ubuntu to be able to run npm install
sudo apt-get -y install npm
npm update
sudo npm install -g yo bower grunt-cli
sudo npm install -g generator-angular

**Comment by feltnerm** [comment]
Did you run `npm i` inside of the project dir? You also need a local `grunt`.

**Comment by jgacuca567** [comment]
@feltnerm  
I ran `npm update` but kept getting the error.

**Comment by yigubigu** [comment]
me to
